config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'likes/index'

  resources :topics do
    resources :bookmarks, except: :index
  end

  resources :bookmarks, except: :index do
    resources :likes, only: [:index, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/about'

  root 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user = current_user
    #authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating bookmark. Please try again."
      redirect_to @topic
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    #authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated successfully."
      redirect_to topic_path(@topic)
    else
      flash.now[:alert] = "There was an error saving the bookmark. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    #authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
      redirect_to topic_path(@topic)
    else
      flash.now[:alert] = "There was an error deleting the bookmark."
      redirect_to topic_path(@topic)
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

  def user_not_authorized
    flash[:alert] = "You must be an owner or an admin to do that."
    redirect_to root_path
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  def create
  @user = User.find_by(email: params[:sender])

  if @user.nil?
    @user = User.create(email: params[:sender], password: "junk")
    @user.save
  end

  @topic = Topic.find_or_create_by(title: params[:subject], user_id: @user.id)

  @bookmark = @topic.bookmarks.find_or_create_by(url: params["body-plain"])

  head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)
    authorize like

    if like.save
      flash[:notice] = "Bookmark successfully liked."
<<<<<<< HEAD
    else
      flash[:alert] = "Failed to like this bookmark."
    end
    redirect_to @bookmark.topic
=======
      redirect_to :back
    else
      flash[:alert] = "Failed to like this bookmark."
      redirect_to :back
    end
>>>>>>> aee390eeefb3b79e45dd86f6f6cf043c7e913595
  end

  def destroy
    bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])
    authorize like

    if like.destroy
      flash[:notice] = "Bookmark unliked."
<<<<<<< HEAD
    else
      flash[:alert] = "Unliking failed."
    end
    redirect_to bookmark.topic
=======
      redirect_to :back
    else
      flash[:alert] = "Unliking failed."
      redirect_to :back
    end
>>>>>>> aee390eeefb3b79e45dd86f6f6cf043c7e913595
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = current_user
    @topic = Topic.new(topic_params)
    @topic.user_id = @user.id

    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @bookmarks = Topic.bookmarks.find(params[:id])
    @bookmarks = @topic.bookmarks
    @topic.bookmarks.assign_attributes(post_params)

    if @topic.bookmarks.save
      @topic.bookmarks.labels = Label.update_labels(params[:topic][:bookmark])
      flash[:notice] = "Bookmark was updated successfully."
      redirect_to [@topic.bookmarks, @topic]
    else
      flash.now[:alert] = "There was an error saving the bookmark. Please try again."
      render :edit
    end
  end

  def destroy
    @topic.bookmarks = Topic.find(params[:id])
    if @topic.bookmarks.destroy
      flash[:notice] = "Topic was successfully deleted."
      redirect_to topics_path
    else
      flash[:alert] = "Error deleting topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # populate @user_bookmarks with the user's bookmarks
    @user_bookmarks = current_user.bookmarks.group_by{|b| b.topic}
    # populate @liked_bookmarks with liked bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]
  
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= content_tag :tr, class: "media", id: "bookmark-#{bookmark.url}" do %>
  <td><%= link_to bookmark.url %></td>
  <td><%= link_to "Edit Bookmark", edit_topic_bookmark_path(bookmark.topic, bookmark), class: 'btn btn-success' %></td>
  <td><%= link_to "Delete Bookmark", [bookmark.topic, bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' } %></td>
  <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
<% end %>

app/views/bookmarks/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [@topic, @bookmark] do |f| %>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "url" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>
</div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
<%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark } %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "All Topics", topics_path %> </li>
        <li><%= link_to "My Bookmarks", users_show_path %> </li>
      <% end %>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>
  </div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.title, topic %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="col-md-4">
  <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
  <div class="row">
    <div class="col-md-8">
      <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "New Topic Title" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<br>

<br>
<% if current_user %>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
  </div>
<% end %>

<%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-primary' %>

<br>
<br>

<h3>Bookmarks</h3>

<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <table class="table table-hover">
          <tbody>
            <tr class='js-items'>
              <%= render @bookmarks %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>My Bookmarks</h3>

<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <table class="table table-hover">
          <tbody>
            <tr class='js-items'>
              <% @user_bookmarks.each do |topic, bookmarks| %>
                <% bookmarks.each do |bookmark| %>
                  <%= render partial: 'bookmarks/bookmark', locals: { bookmark: bookmark } %>
                <% end %>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<h3>My Likes</h3>

<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <table class="table table-hover">
          <tbody>
            <tr class='js-items'>
              <% @liked_bookmarks.each do |bookmark| %>
                <td><%= link_to bookmark.url %></td>
                <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>

app/views/welcome/about.html.erb
<h1>About Blocmarks</h1>
<h3>Blocmarks is an application that allows a user to bookmark URLs via email, peruse other user's bookmarks and maintain a personal index of categorized bookmarks.</h3>
<p>Created by: Camille Seguette</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmarks.</h1>
<p>Blocmarks allows you to peruse other user's bookmarks and maintain a personal index of categorized bookmarks.</p>